apiVersion: v1
kind: Service
metadata:
  name: biddinggo-frontend-service
  namespace: biddinggo
  labels:
    app: biddinggo-frontend
spec:
  type: ClusterIP
  selector:
    app: biddinggo-frontend
  ports:
    - name: http
      port: 80
      targetPort: http
